# Generated by Django 4.2.19 on 2025-03-23 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workoutsession_created_at_workoutsession_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fitness_goal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workout_location',
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instruction',
            field=models.TextField(blank=True, help_text='How to perform the exercise properly', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='Users personal bio', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_trainer',
            field=models.BooleanField(default=False, help_text='Wether this user is a trainer'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this workout plan is public or not'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutpreferences',
            name='excluded_exercises',
            field=models.JSONField(default=list, help_text='Exercises to avoid'),
        ),
        migrations.AddField(
            model_name='workoutpreferences',
            name='focus_areas',
            field=models.JSONField(default=list, help_text='Specific body areas to focus'),
        ),
        migrations.AddField(
            model_name='workoutpreferences',
            name='height',
            field=models.FloatField(blank=True, default=0, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='workoutpreferences',
            name='injuries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutpreferences',
            name='time_per_session',
            field=models.IntegerField(default=45, help_text='Time in minutes'),
        ),
        migrations.AddField(
            model_name='workoutpreferences',
            name='weight',
            field=models.FloatField(blank=True, default=0, help_text='Weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('arms', 'Arms'), ('shoulders', 'Shoulders'), ('abs', 'Abs'), ('core', 'Core'), ('glutes', 'Glutes'), ('cardio', 'Cardiovascular'), ('other', 'Other'), ('none', 'None'), ('full_body', 'Full Body')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
