# Generated by Django 4.2.19 on 2025-03-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_fitness_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutpreferences',
            name='time_per_session',
        ),
    ]
